# This is a basic workflow to help you get started with Actions

name: Terraform Actions

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  first-job:
    runs-on: ubuntu-latest
    steps:
      # - name: Load Env Variables
      #   run: cat ../../../env.yaml >> $GITHUB_ENV
      - name: Get code
        uses: actions/checkout@v3
      - name: Print greeting
        run: echo "Hello World"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: Test if works
        run: echo ${{ github.workspace }}
      - name: list files in workspace
        run: ls -la ${{ github.workspace }}
      - name: list files in GITHUB_WORKSPACE
        run: ls -la $GITHUB_WORKSPACE
      # - name: view $GITHUB_ENV
      #   run: echo $GITHUB_ENV
      # - name: update env vars
      #   run: sh ${{ github.workspace }}/.github/workflows/convert.sh ${{ github.workspace }}/dev.vars.yaml
      # - name: view $GITHUB_ENV
      #   run: echo $GITHUB_ENV
      # - name: View motsId
      #   run: echo $motsId
      # - name: View name
      #   run: echo $name

      - name: Replace Tokens
        uses: qetza/replacetokens-action@v1
        with:
          sources: |
            **/*.tfvars
            **/*.tf
            **/*.sh
            **/*.ps1
            **/*.tmpl
            **/*.tpl
            **/*.json
            **/*.conf
          root: '${{ github.workspace }}'
          log-level: 'warn'
          token-prefix: '[__'
          token-suffix: '__]'
          variables: '${{ github.workspace }}/dev.vars.(json|jsonc)'

      - name: View file
        run: cat ${{ github.workspace }}/vars.auto.tfvars
